#!/bin/sh
#support MT6620 WIFI Module
  mknod /dev/stpwmt c 190 0
  mknod /dev/stpgps c 191 0
  mknod /dev/fm c 193 0
  mknod /dev/wmtWifi c 194 0

  insmod /lib/modules/mt6620/mtk_hif_sdio.ko
  insmod /lib/modules/mt6620/mtk_stp_wmt.ko
  insmod /lib/modules/mt6620/mtk_stp_uart.ko
  insmod /lib/modules/mt6620/mtk_stp_gps.ko
  #insmod /lib/modules/mt6620/hci_stp.ko
  #insmod /lib/modules/mt6620/mt6620_fm_drv.ko
  #insmod /lib/modules/mt6620/mtk_fm_priv.ko
  insmod /lib/modules/mt6620/mtk_wmt_wifi.ko WIFI_major=194
  insmod /lib/modules/mt6620/wlan_mt6620.ko

  chmod 0666 /dev/stpwmt
  chmod 0666 /dev/stpgps
  chmod 0666 /dev/fm
  chmod 0666 /dev/wmtWifi
  chmod 0666 /dev/gps
  chmod 0660 /dev/ttyAMA2

  /usr/bin/6620_launcher -m 1 -b 921600 -n /etc/firmware/mt6620_patch_hdr.bin -d /dev/ttyAMA2 &

  sleep 4
  echo 1 > /dev/wmtWifi
  sleep 4
  echo AP > /dev/wmtWifi

  ifconfig wlan0 192.168.2.1 netmask 255.255.255.0

  mkdir -p /var/lib/misc/
  touch /var/lib/misc/udhcpd.leases
  udhcpd -f /etc/udhcpd.conf &
  
  iptables -A FORWARD -s 192.168.2.0/24 -o eth0 -j ACCEPT
  iptables -A FORWARD -d 192.168.4.0/24 -j ACCEPT
  iptables -t nat -A POSTROUTING -s 192.168.2.0/255.255.255.0 -o eth0 -j MASQUERADE
  echo 1 >/proc/sys/net/ipv4/ip_forward 

  cd /etc/hostapd
  hostapd -B hostapd.conf
